[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
sqlx = { workspace = true }
template = { workspace = true }

[dev-dependencies]
database = { workspace = true }
expect-test = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
