[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
api = { path = "crates/api" }
askama = { version = "0.16.0", default-features = false, features = ["derive", "std"] }
axum = { version = "0.8.9", default-features = false, features = ["http1", "tokio"] }
database = { path = "crates/database" }
expect-test = "1.5.1"
reqwest = { version = "0.12", default-features = false }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "migrate", "macros"] }
template = { path = "crates/template" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net"] }
tower = { version = "0.5.3", features = ["util"] }
